### ISSUE TITLE
Mounted MG Ammo in Req Office Assort

### ISSUE THREAD

**Issue by PhantomInTime** [KillerDJLang/Raid-Overhaul#16]
![image_2024-07-13_044223170](https://github.com/user-attachments/assets/0d4dbdaf-998a-42c1-bdfa-029ff6e43982)

May be worth checking for the grenades for the mounted GL as well.

**Comment by KillerDJLang** [comment]
Removed the ammo for the next version and double checked that the mounted 30x29 grenade launcher ammo was removed as well
