### ISSUE TITLE
Adrenaline Effect Causes Massive Stamina Loss On Hit with No PK Effect

### ISSUE THREAD

**Issue by PhantomInTime** [KillerDJLang/Raid-Overhaul#17]
Whenever you take any form of bullet damage, an extreme amount of stamina drain is applied. For essentially all rifle calibers, this results in an instant loss of all stamina. On live, this stamina loss was greatly reduced. Will require more testing to determine the cause.

[LogOutput.log](https://github.com/user-attachments/files/16201822/LogOutput.log)
[server-2024-07-13.log](https://github.com/user-attachments/files/16201824/server-2024-07-13.log)
[log_2024.07.13_10-17-14_0.14.9.1.30626.zip](https://github.com/user-attachments/files/16201835/log_2024.07.13_10-17-14_0.14.9.1.30626.zip)

Clip example: https://streamable.com/u1ronk
Clip example of non-RO Tarkov: https://streamable.com/fbmpi4

**Comment by PhantomInTime** [comment]
I was able to narrow it down to the Adrenaline effect. I'm unsure what the intention of the function is, but it's the cause of the drainage and does not apply any kind of painkiller effect like Kobra's original mod did.

**Comment by KillerDJLang** [comment]
Removed adrenaline as a whole for the next update since the solutions I had would be irrelevant with the new recoil system and stamina loss changes from live in place

May revisit in the future to make a new more unique effect, but no ideas on that currently
