### ISSUE TITLE
Hope its ok

### ISSUE THREAD

**Issue by ThislsName** [KillerDJLang/Raid-Overhaul#21]
Just wanted to tell you that in SPT 3.10.1 airdrops are back on the menu. Fellas just forgot to enable them on release.
I assume you just commented out airdrops and exfil crate?
Thanks for the mod mate.

**Comment by KillerDJLang** [comment]
It's not that. I did comment them out but the way that airdrops actually function was completely changed from the old spt system to the pve system. So I will have to rewrite all of it on the client side to the new way which is going to be rather time consuming
