### ISSUE TITLE
Black Screen when leaving Raid

### ISSUE THREAD

**Issue by vFize** [KillerDJLang/Raid-Overhaul#23]
All I can really say is that if I use this mod with MOAR when I exfil or die a bunch of error codes come up for boss spawn chance and blah blah blah, I imagine it some how conflicts with that mod atm. If you want screenshots I'll have to redownload your mod

**Comment by KillerDJLang** [comment]
Im aware and passed it along to Dewar. Going to see if I can fix it from my end but it works fine without moar and with other spawn mods/earlier versions of moar so not at the top of my list

**Comment by KillerDJLang** [comment]
Im aware and passed it along to Dewar. Going to see if I can fix it from my end but it works fine without moar and with other spawn mods/earlier versions of moar so not at the top of my list
